"""Admin configuration for Senior Guidance."""
from django.conf import settings
from django.contrib import admin, messages
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.utils.crypto import get_random_string

from .models import MentorProfile, MentorRequest, ChatMessage, validate_nitp_email


@admin.register(MentorProfile)
class MentorProfileAdmin(admin.ModelAdmin):
	list_display = ['user', 'branch', 'year', 'is_approved', 'created_at']
	list_filter = ['is_approved', 'branch', 'year', 'created_at']
	search_fields = ['user__email', 'user__first_name', 'user__last_name']
	readonly_fields = ['created_at']
	actions = ['verify_and_send_credentials']

	def verify_and_send_credentials(self, request, queryset):
		"""Approve mentors and email autogenerated passwords."""
		User = get_user_model()
		updated = 0
		for profile in queryset:
			try:
				validate_nitp_email(profile.user)
			except ValidationError as exc:
				self.message_user(request, f"{profile.user.email}: {exc}", level=messages.ERROR)
				continue

			if not profile.user.password:
				password = get_random_string(12)
				profile.user.set_password(password)
				profile.user.save(update_fields=['password'])
			else:
				password = get_random_string(12)
				profile.user.set_password(password)
				profile.user.save(update_fields=['password'])

			profile.is_approved = True
			profile.save(update_fields=['is_approved'])

			send_mail(
				subject="Innovation Hub | Mentor Access Approved",
				message=(
					"Hi, your mentor profile is approved.\n"
					f"Email: {profile.user.email}\n"
					f"Password: {password}\n"
					"Login via /admin/login/ or designated portal."
				),
				from_email=getattr(settings, 'DEFAULT_FROM_EMAIL', 'no-reply@nitp.ac.in'),
				recipient_list=[profile.user.email],
				fail_silently=True,
			)
			updated += 1

		self.message_user(request, f"{updated} mentor accounts verified and credentials sent.")

	verify_and_send_credentials.short_description = 'Verify and Send Email Credentials'


@admin.register(MentorRequest)
class MentorRequestAdmin(admin.ModelAdmin):
	list_display = ['student', 'mentor', 'status', 'created_at', 'student_whatsapp']
	list_filter = ['status', 'created_at']
	search_fields = ['student__email', 'mentor__user__email', 'message']
	readonly_fields = ['created_at', 'approved_at']


@admin.register(ChatMessage)
class ChatMessageAdmin(admin.ModelAdmin):
	list_display = ['request', 'sender', 'sent_at']
	list_filter = ['sent_at']
	search_fields = ['message', 'sender__email']
