# Generated by Django 6.0.1 on 2026-01-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('semester', models.IntegerField(choices=[(1, 'Sem 1'), (2, 'Sem 2'), (3, 'Sem 3'), (4, 'Sem 4'), (5, 'Sem 5'), (6, 'Sem 6'), (7, 'Sem 7'), (8, 'Sem 8')])),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='vault.branch')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['semester', 'name'],
                'unique_together': {('branch', 'code', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('PYQ', 'Previous Year Question'), ('NOTES', 'Notes'), ('BOOK', 'Book/Reference')], max_length=10)),
                ('exam_type', models.CharField(choices=[('MID', 'Mid-Semester'), ('END', 'End-Semester'), ('QUIZ', 'Quiz'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('file_url', models.URLField(help_text='Google Drive link or external URL')),
                ('uploaded_by', models.CharField(blank=True, help_text='Name of contributor', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='vault.subject')),
            ],
            options={
                'verbose_name_plural': 'Resources',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['subject', 'resource_type'], name='vault_resou_subject_f38000_idx'), models.Index(fields=['is_active', 'is_verified'], name='vault_resou_is_acti_5ff416_idx')],
            },
        ),
    ]
