# Generated by Django 6.0.1 on 2026-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BentoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Lucide icon name (e.g., 'library', 'users', 'trending-up')", max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('grid_cols', models.IntegerField(default=1, help_text='Grid columns span (1-4)')),
                ('grid_rows', models.IntegerField(default=1, help_text='Grid rows span (1-2)')),
                ('bg_color', models.CharField(default='bg-zinc-900/20', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bento Card',
                'verbose_name_plural': 'Bento Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navbar Link',
                'verbose_name_plural': 'Navbar Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Innovation Hub', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('vision_statement', models.TextField(default='Beyond placements: To build a culture at NIT Patna where students learn from each other, explore innovation fearlessly, share knowledge selflessly, and grow into engineers who create solutions — not just resumes.')),
                ('footer_text', models.CharField(default='© 2026 Innovation Hub NIT Patna • By Students, For Students', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
