# Generated by Django 6.0.1 on 2026-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ECE', 'Electronics & Communication'), ('CSE', 'Computer Science'), ('SOFTWARE', 'Software Development'), ('HARDWARE', 'Hardware/VLSI'), ('STARTUP', 'Startup & Entrepreneurship'), ('RESEARCH', 'Research & Academia'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Brief summary of the roadmap')),
                ('content_link', models.URLField(help_text='Google Drive or Notion link')),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guidance Roadmap',
                'verbose_name_plural': 'Guidance Roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student Inquiry',
                'verbose_name_plural': 'Student Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('ARCH', 'Architecture'), ('OTHER', 'Other')], max_length=10)),
                ('year', models.IntegerField(choices=[(2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, 'PG/PhD')])),
                ('expertise', models.TextField(help_text='Areas of expertise (e.g., Web Dev, Arduino, ML)')),
                ('linkedin_profile', models.URLField(blank=True)),
                ('github_profile', models.URLField(blank=True)),
                ('why_mentor', models.TextField(blank=True, help_text='Why do you want to become a mentor?')),
                ('is_approved', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mentor Application',
                'verbose_name_plural': 'Mentor Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
