# Generated by Django 6.0.1 on 2026-01-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guidanceroadmap_inquiry_mentorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='student_whatsapp',
            field=models.CharField(default='', help_text='WhatsApp number (visible to mentors)', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='mentor_whatsapp',
            field=models.CharField(default='', help_text='WhatsApp number (private, not shown publicly)', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='guidance_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='guidance/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='guidance_video_url',
            field=models.URLField(blank=True, help_text='Hero section video link for guidance page'),
        ),
    ]
